version: "3.9"

services:
  dyrtransportes-react-test:
    image: localhost:5000/dyrtransportes/dev/dyrtransportes-react-test:latest
    
    ports:
      - 1002:80

    environment:
      - VITE_API_URL=localhost_url

    container_name: dyrtransportes-react-test

    networks:
      - dyrtransportes
      - dyrtransportes-frontend

networks:
  dyrtransportes:
  dyrtransportes-frontend: