version: "3.9"

services:
  dyrtransportes-react-prod:
    image: ${REGISTRY}/dyrtransportes/frontend/prod/dyrtransportes-react:latest
    
    ports:
      - 1000:80

    environment:
      - VITE_API_URL=http://dyrtransportes-flask-dev:8081

    container_name: dyrtransportes-react-prod

    networks:
      - dyrtransportes
      - dyrtransportes-frontend

networks:
  dyrtransportes:
  dyrtransportes-frontend: