version: "3.9"

services:
  dyrtransportes-react-dev:
    image: ${REGISTRY}/dyrtransportes/frontend/dev/dyrtransportes-react:latest
    
    ports:
      - 1002:80

    environment:
      - VITE_API_URL=http://dyrtransportes-flask-dev:8081

    container_name: dyrtransportes-react-dev

    networks:
      - dyrtransportes-frontend
      - dyrtransportes

networks:
  dyrtransportes-frontend:
  dyrtransportes:
    name: dyrtransportes
    external: true