version: "3.9"

services:
  dyrtransportes-react-rc:
    image: ${REGISTRY}/dyrtransportes/frontend/rc/dyrtransportes-react:latest
    
    ports:
      - 1001:80

    environment:
      - VITE_API_URL=http://dyrtransportes-flask-dev:8081

    container_name: dyrtransportes-react-rc

    networks:
      - dyrtransportes
      - dyrtransportes-frontend

networks:
  dyrtransportes:
  dyrtransportes-frontend: