# Steps (desde root del proyecto)
# 1. Agregar token para Sonarqube
# 2. docker build --network=host -t node-agent:latest -f jenkins/Dockerfile.agent .
# 4. docker tag node-agent:latest localhost:5000/dyrtransportes/agent/node-agent:20.11
# 5. docker push localhost:5000/dyrtransportes/agent/node-agent:20.11

FROM node:20.11

# Add Docker's official GPG key:
RUN apt-get -y update
RUN apt-get -y install ca-certificates curl gnupg
RUN install -m 0755 -d /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
RUN chmod a+r /etc/apt/keyrings/docker.gpg

# Add the repository to Apt sources:
RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    tee /etc/apt/sources.list.d/docker.list > /dev/null

#Install Docker CLI
RUN apt-get -y update
RUN apt-get -y install docker-ce-cli

#Jenkins user (node user already exists)
# RUN groupadd --gid 1000 jenkins \
#     && useradd --uid 1000 --gid jenkins --shell /bin/bash --create-home jenkins


# sonarqube scanner
RUN npm install -g sonarqube-scanner

COPY . /app
WORKDIR /app

RUN chmod -R 777 . \
    && chown -R 1000:1000 .

#Cache npm install and sonar scanner
USER node

RUN sonar-scanner --version

RUN npm cache clean --force \
    && npm install && npm audit fix

RUN sonar-scanner -Dsonar.projectKey=D-y-R-Transportes-React \
    -Dsonar.sourceEncoding=UTF-8 \
    -Dsonar.host.url=http://localhost:9000 \
    -Dsonar.token=squ_c488cbd9ea025f37144717a733671d127306938a

USER root
RUN cp -r /app/node_modules /home/node/node_modules \
    && chmod -R 777 /home/node \
    && chown -R 1000:1000 /home/node

RUN rm -rf /app/

USER jenkins
WORKDIR /app